In [1]:
import numpy as np
import pandas as pd


In [3]:
from sklearn.datasets import load_digits


In [4]:
digits = load_digits()

In [6]:
f= pd.DataFrame(digits.data)
t = pd.DataFrame(digits.target)

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X=f
y=t

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)


In [10]:
from sklearn.svm import SVC
from sklearn.metrics import classification_report,confusion_matrix

In [12]:
svclassifier = SVC(kernel='linear', degree=8)  
svclassifier.fit(X_train, y_train) 
y_pred1 = svclassifier.predict(X_test)
print ("kernel = 'linear'\n")
print ("Confusion Matrix:\n",confusion_matrix(y_test, y_pred1))
print ("\n\nClassification Report:\n", classification_report(y_test, y_pred1))

kernel = 'linear'

Confusion Matrix:
 [[55  0  0  0  0  0  0  0  0  0]
 [ 0 53  0  0  1  0  0  0  1  0]
 [ 0  0 52  0  0  0  0  0  0  0]
 [ 0  0  0 54  0  1  0  0  1  0]
 [ 0  0  0  0 64  0  0  0  0  0]
 [ 0  0  0  0  0 71  0  1  0  1]
 [ 0  0  0  0  0  0 57  0  0  0]
 [ 0  0  0  0  0  0  0 61  0  1]
 [ 0  1  0  1  0  1  0  0 49  0]
 [ 0  0  0  0  1  0  0  0  1 66]]


Classification Report:
              precision    recall  f1-score   support

          0       1.00      1.00      1.00        55
          1       0.98      0.96      0.97        55
          2       1.00      1.00      1.00        52
          3       0.98      0.96      0.97        56
          4       0.97      1.00      0.98        64
          5       0.97      0.97      0.97        73
          6       1.00      1.00      1.00        57
          7       0.98      0.98      0.98        62
          8       0.94      0.94      0.94        52
          9       0.97      0.97      0.97        68

avg / total       0.

C:\Program FilesC\Program Files\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [15]:
svclassifier = SVC(kernel='poly', degree=8)  
svclassifier.fit(X_train, y_train) 
y_pre2 = svclassifier.predict(X_test)
print ("kernel = 'poly'\n")
print ("Confusion Matrix:\n",confusion_matrix(y_test, y_pre2))
print ("\n\nClassification Report:\n", classification_report(y_test, y_pre2))

kernel = 'poly'

Confusion Matrix:
 [[55  0  0  0  0  0  0  0  0  0]
 [ 0 50  1  0  0  0  0  0  4  0]
 [ 0  0 52  0  0  0  0  0  0  0]
 [ 0  0  0 54  0  1  0  0  1  0]
 [ 0  0  0  0 64  0  0  0  0  0]
 [ 0  0  0  0  1 72  0  0  0  0]
 [ 0  0  0  0  0  0 57  0  0  0]
 [ 0  0  0  0  0  0  0 61  0  1]
 [ 0  3  0  0  0  0  0  0 48  1]
 [ 0  0  0  2  1  0  0  0  0 65]]


Classification Report:
              precision    recall  f1-score   support

          0       1.00      1.00      1.00        55
          1       0.94      0.91      0.93        55
          2       0.98      1.00      0.99        52
          3       0.96      0.96      0.96        56
          4       0.97      1.00      0.98        64
          5       0.99      0.99      0.99        73
          6       1.00      1.00      1.00        57
          7       1.00      0.98      0.99        62
          8       0.91      0.92      0.91        52
          9       0.97      0.96      0.96        68

avg / total       0.97

C:\Program FilesC\Program Files\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [16]:
svclassifier = SVC(kernel='rbf')  
svclassifier.fit(X_train, y_train) 
y_pre3 = svclassifier.predict(X_test)
print ("When kernel = 'rbf'\n")
print ("Confusion Matrix:\n",confusion_matrix(y_test, y_pre3))
print ("\n\nClassification Report:\n", classification_report(y_test, y_pre3))

C:\Program FilesC\Program Files\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


When kernel = 'rbf'

Confusion Matrix:
 [[26  0  0 29  0  0  0  0  0  0]
 [ 0 23  0 32  0  0  0  0  0  0]
 [ 0  0 34 18  0  0  0  0  0  0]
 [ 0  0  0 56  0  0  0  0  0  0]
 [ 0  0  0 44 20  0  0  0  0  0]
 [ 0  0  0 72  0  1  0  0  0  0]
 [ 0  0  0 17  0  0 40  0  0  0]
 [ 0  0  0 42  0  0  0 20  0  0]
 [ 0  0  0 37  0  0  0  0 15  0]
 [ 0  0  0 65  0  0  0  0  0  3]]


Classification Report:
              precision    recall  f1-score   support

          0       1.00      0.47      0.64        55
          1       1.00      0.42      0.59        55
          2       1.00      0.65      0.79        52
          3       0.14      1.00      0.24        56
          4       1.00      0.31      0.48        64
          5       1.00      0.01      0.03        73
          6       1.00      0.70      0.82        57
          7       1.00      0.32      0.49        62
          8       1.00      0.29      0.45        52
          9       1.00      0.04      0.08        68

avg / total       

In [17]:
svclassifiersvclass  = SVC(kernel='sigmoid')  
svclassifier.fit(X_train, y_train) 
y_pre4 = svclassifier.predict(X_test)
print ("When kernel = 'sigmoid'\n")
print ("Confusion Matrix:\n",confusion_matrix(y_test, y_pre4))
print ("\n\nClassification Report:\n", classification_report(y_test, y_pre4))

C:\Program FilesC\Program Files\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


When kernel = 'sigmoid'

Confusion Matrix:
 [[26  0  0 29  0  0  0  0  0  0]
 [ 0 23  0 32  0  0  0  0  0  0]
 [ 0  0 34 18  0  0  0  0  0  0]
 [ 0  0  0 56  0  0  0  0  0  0]
 [ 0  0  0 44 20  0  0  0  0  0]
 [ 0  0  0 72  0  1  0  0  0  0]
 [ 0  0  0 17  0  0 40  0  0  0]
 [ 0  0  0 42  0  0  0 20  0  0]
 [ 0  0  0 37  0  0  0  0 15  0]
 [ 0  0  0 65  0  0  0  0  0  3]]


Classification Report:
              precision    recall  f1-score   support

          0       1.00      0.47      0.64        55
          1       1.00      0.42      0.59        55
          2       1.00      0.65      0.79        52
          3       0.14      1.00      0.24        56
          4       1.00      0.31      0.48        64
          5       1.00      0.01      0.03        73
          6       1.00      0.70      0.82        57
          7       1.00      0.32      0.49        62
          8       1.00      0.29      0.45        52
          9       1.00      0.04      0.08        68

avg / total   